### ISSUE TITLE
accessing a tag's name

### ISSUE THREAD

**Issue by jabbalaci** [stchris/untangle#14]
I wanted to get the name of a tag and I could do it by writing `tag._name`. The underscrose suggests that it's a private variable but getting a tag's name is a common task, thus there should be a public way to do it. `tag.name` didn't work while it seemed to be the intuitive solution.

**Comment by marty331** [comment]
I'm attempting to get the cdata value but am getting an error, here is my loop:
for entry in obj.feed.entry:
   geoc = entry.cap_geocode.valueName
   geod = entry.cap_geocode.value.cdata
   print(geoc, geod)

I'm getting this error:
AttributeError: 'list' object has no attribute 'cdata'


If I remove the ".cdata" I get the following:
([Element(name = valueName, attributes = {}, cdata = FIPS6), Element(name = valueName, attributes = {}, cdata = UGC)], [Element(name = value, attributes = {}, cdata = 054003 054023 054027 054031 054037 054057 054065 054071), Element(name = value, attributes = {}, cdata = WVZ050 WVZ051 WVZ052 WVZ053 WVZ055 WVZ501 WVZ502 WVZ503 WVZ504 WVZ505 WVZ506)])

**Comment by stchris** [comment]
@marty331 can you please open a new issue and also add (parts of) the xml file you are trying to parse?

**Comment by marty331** [comment]
I figured it out:
geod = entry.cap_geocode.value[0].cdata

Now it works, in fact I have already rewritten production code using your library.

**Comment by stchris** [comment]
Glad you figured it out, @marty331. And even more so if you like the library.
