### ISSUE TITLE
Using untangle, how can I check the existence of attributes and tags in XML before parsing

### ISSUE THREAD

**Issue by Nouri1111** [stchris/untangle#28]
I'm parsing an XML file via untangle in python and and writing the content to a database.

The content of children tags will be variant for different tags. For example first event tag has party tag as child but second event tag doesn't have.
How can I check whether a tag exists or not before parsing?

code
doc = untangle.parse(file.xml)
for title  in doc.groupInformation.group:
    print 'Title : %s' % ','.join([Title.cdata for Title in title.BasicDescription.Title])

Result:
raise IndexError('Unknown key <%s>' % key)
IndexError: Unknown key </p>

**Comment by Nouri1111** [comment]
<groupInformation>
			<Group groupId="7" ">
				<GroupType xsi: value="seri"/>
				<BasicDescription>
					<Title xml:lang="en" type="seriesTitle">hello +</Title>
					<Title xml:lang="de" type="seriesTitle">hello +</Title>
					<Material>
						<elated href="Cover">
							<Name xml:lang="de">Box cover</Name>
						</elated>
						<MediaLocator>
							<MediaUri xmlns="0fe52f1.jpg</MediaUri>
						</MediaLocator>
					</Material>
					<Material>
						<elated href="rity.5">
							<Name xml:lang="de">ity.5</Name>
						</elated>
						<MediaLocator>
							<MediaUri xmlns="22d1.jpg</MediaUri>
						</MediaLocator>
					</Material>
				</BasicDescription>
				<OtherIdentifier>140251927</OtherIdentifier>
			</Group>
			<Group groupId="157" >
				<GroupType xsi:type="ProgramGroupTypeType" value="series"/>
				<BasicDescription/>
				<OtherIdentifier type="objectid" organization="RBM" authority="RBM">140096500157</OtherIdentifier>
			</Group>
			<Group groupId="95" >
				<GroupType xsi:type="ProgramGroupTypeType" value="series"/>
				<BasicDescription/>
				<OtherIdentifier>5094784</OtherIdentifier>
			</Group>
		</groupInformation>

**Comment by Nouri1111** [comment]
<groupInformation>
	<Group groupId="7" ">
		<GroupType xsi: value="seri"/>
		<BasicDescription>
			<Title xml:lang="en" type="seriesTitle">hello +</Title>
			<Title xml:lang="de" type="seriesTitle">hello +</Title>
			<Material>
				<elated href="Cover">
					<Name xml:lang="de">Box cover</Name>
				</elated>
				<MediaLocator>
					<MediaUri xmlns="0fe52f1.jpg</MediaUri>
				</MediaLocator>
			</Material>
			<Material>
				<elated href="rity.5">
					<Name xml:lang="de">ity.5</Name>
				</elated>
				<MediaLocator>
					<MediaUri xmlns="22d1.jpg</MediaUri>
				</MediaLocator>
			</Material>
		</BasicDescription>
		<OtherIdentifier>140251927</OtherIdentifier>
	</Group>
	<Group groupId="157" >
		<GroupType xsi:type="ProgramGroupTypeType" value="series"/>
		<BasicDescription/>
		<OtherIdentifier type="objectid" organization="RBM" authority="RBM">140096500157</OtherIdentifier>
	</Group>
	<Group groupId="95" >
		<GroupType xsi:type="ProgramGroupTypeType" value="series"/>
		<BasicDescription/>
		<OtherIdentifier>5094784</OtherIdentifier>
	</Group>
</groupInformation>

**Comment by GusBricker** [comment]
Issue #37 doesn't actually answer this question as this is related to finding an attribute within an element, not the existence of an element.

**Comment by GusBricker** [comment]
Some further looking over the code, the best way is:

After looking at the code, the way to achieve this:
```
if obj.x.data.get_attribute('someattr'):
   print x.data['someattr'] # Prints 123
```

Assumes the following XML:
```
<x>
   <data someattr='123'/>
</x>
```
