### ISSUE TITLE
can't dir() the parsed object

### ISSUE THREAD

**Issue by iffy** [stchris/untangle#5]
I'm not sure if this is a SAX problem.  If it is, just close it.  But here's the problem:

``` python
>>> filename = 'posts-july-2012.xml'
>>> from untangle import parse
>>> o = parse(filename)
>>> dir(o)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/untangle.py", line 66, in __getattr__
    raise IndexError('Unknown key <%s>' % key)
IndexError: Unknown key <__dir__>
```

**Comment by Nouri1111** [comment]
I'm parsing an XML file via untangle in python and and writing the content to a database.

The content of children tags will be variant for different tags. For example first event tag has party tag as child but second event tag doesn't have.
 How can I check whether a tag exists or not before parsing? 
raise IndexError('Unknown key <%s>' % key)
IndexError: Unknown key <Title>
