### ISSUE TITLE
Outdated version on PyPI

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [stchris/untangle#50]
Hello dear friend,

Thanks for your awesome work, however the version here on github is way ahead than the one on PyPI.
Do you think it would possible to send a minor version on PyPI ?

https://pypi.python.org/pypi/untangle/json

This json file is so old and it gives us some trouble because no "classifier" is reported in your package...
It flags the package as non Python3 compatible and thus we have many issues with our continuous integrations services ...

I would greatly appreciate a little update on PyPI or at least to get a date when you think releasing.

I can help you fixing this if you want to and implement an automatic github and PyPI release when you commit a new tag. Would you be interested @stchris ?

Thanks for your time,

Best Regards,

Jonathan

**Comment by stchris** [comment]
`1.1.1` fixed this.

**Comment by DEKHTIARJonathan** [comment]
@stchris: absolutely not fixed! Please reopen the issue:

https://pypi.python.org/pypi/untangle/json

```
info": {
    "package_url": "http://pypi.python.org/pypi/untangle",
    "author": "Christian Stefanescu",
    "author_email": "st.chris@gmail.com",
    "version": "1.1.1",
    "classifiers": [
      
    ],
```

I don't know where can be the issue, the PKG-INFO displays the classifiers correctly...
Maybe there have been a problem on PyPI... Moreover the git tag and release for v1.1.1 is not created ;)

```
Platform: UNKNOWN
Classifier: Development Status :: 5 - Production/Stable
Classifier: Intended Audience :: Developers
Classifier: Natural Language :: English
Classifier: License :: OSI Approved :: MIT License
Classifier: Programming Language :: Python
Classifier: Programming Language :: Python :: 2.6
Classifier: Programming Language :: Python :: 2.7
Classifier: Programming Language :: Python :: 3.3
Classifier: Programming Language :: Python :: 3.4
Classifier: Programming Language :: Python :: 3.5
Classifier: Programming Language :: Python :: 3.6
```
