### ISSUE TITLE
XML is okay but I get a strange error

### ISSUE THREAD

**Issue by tvdsluijs** [stchris/untangle#59]
```
Element <None> with attributes None, children [Element(name = products, attributes = {}, cdata = 

)] and cdata 
None
```
I have no idea why. But the XML is okay.

**Comment by stchris** [comment]
@tvdsluijs can you provide an xml snippet and your code to reproduce this issue?

**Comment by tvdsluijs** [comment]
hi stchris, I have to look it up. Have not worked with it a long time

**Comment by stchris** [comment]
Feel free to reopen if this is still an issue and there are reproduction steps available
