### ISSUE TITLE
how to add child/children to the xml file?

### ISSUE THREAD

**Issue by popeaaa** [stchris/untangle#61]
Can anyone give me a example?
Thank you very much

**Comment by stchris** [comment]
Hi @popeaaa ! I'm afraid `untangle` is only able to parse XML files. Changing the content requires some extra steps (or using a different library).

**Comment by popeaaa** [comment]
> Hi @popeaaa ! I'm afraid `untangle` is only able to parse XML files. Changing the content requires some extra steps (or using a different library).

ok,thanks for your answering
