### ISSUE TITLE
Is there easy way get dict? (JSON like) data

### ISSUE THREAD

**Issue by gordio** [stchris/untangle#62]
Is it possible? Like to store data to Json. :)

**Comment by sgaechter** [comment]
Hello @gordio.

There is another Lib who produces dict of XML: [xmltodict](https://pypi.org/project/xmltodict/) Maybe this satisfies your need?
Greez
Sven

**Comment by stchris** [comment]
Closing this issue since `untangle` does just this one thing: it allows one to parse XML documents as Python-like objects.
