### ISSUE TITLE
Make untangle installable from conda-forge?

### ISSUE THREAD

**Issue by HTenkanen** [stchris/untangle#72]
Hi @stchris!

Thanks for creating this very useful package! I use it myself in here: https://github.com/HTenkanen/transx2gtfs

I was just creating a conda-forge recipe for my library, and realized that `untangle` is not currently available from conda. 

Would you be okay with the idea of adding untangle to conda-forge? The thing with conda is, that they are very restrictive that all dependencies of libraries need to come from conda-forge (in this way the reliability of the whole system is ensured). Hence, any libraries that depends on untangle cannot be published in conda-forge easily (such as mine).

If you are open to this idea, I am happy to help with writing a conda-forge recipe for untangle. The process does not require any modifications to the current repo, but the things are done by forking the "conda-forge/staged-recipes" repo.

More information about the whole conda process can be found from here:
https://conda-forge.org/

**Comment by HTenkanen** [comment]
@stchris Hi! Coming back to this. Would you be okay if I publish `untangle` in conda-forge so that it could be installed easily with conda? I can write the recipe and help out maintaining it. If you wish I can add you as one of the recipe-maintainers as well?

**Comment by HTenkanen** [comment]
Untangle is now available also from conda-forge: https://anaconda.org/conda-forge/untangle

It can now be installed with conda by:
`$ conda install -c conda-forge untangle`

**Comment by stchris** [comment]
Sorry for my lack of reaction, I currently have no bandwidth for this project. I have never used conda and don't plan to do so, but I appreciate your work and I don't mind untangle being available there as well.

**Comment by HTenkanen** [comment]
@stchris Sure, no problem! I am happy to help in terms of maintaining the conda feedstock. When ever there is a new release out just ping me, so I can then update the feedstock as well. 👍

**Comment by stchris** [comment]
Thank you for this!
